name: fuzzer
on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  echidna:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: read
      contents: read
      security-events: write
    timeout-minutes: 15
    container:
      image: ghcr.io/nayms/contracts-builder:latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     testName:
    #       - TickBitmapEchidnaTest
    #       - TickMathEchidnaTest
    #       - SqrtPriceMathEchidnaTest
    #       - SwapMathEchidnaTest
    #       - TickEchidnaTest
    #       - TickOverflowSafetyEchidnaTest
    #       - OracleEchidnaTest
    #       - BitMathEchidnaTest
    #       - LowGasSafeMathEchidnaTest
    #       - UnsafeMathEchidnaTest
    #       - FullMathEchidnaTest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update path
        run: echo "/root/.cargo/bin:/root/.foundry/bin" >> $GITHUB_PATH

      - name: Install solc
        run: svm install 0.7.6 && svm install 0.8.13 && svm use 0.8.13

      - name: Install Forge dependencies
        run: forge install

      - name: Install Node dependencies
        run: yarn

      - name: Prepare build
        run: make prep-build

      # - name: Build solidity contracts
      #   run: make build

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          files: test/invariants/FuzzyDiamond.sol
          config: echidna.config.yml
          # corpus-dir: corpus
          # test-mode: assertion
          # test-limit: 250000
          # seq-len: 100
          # solc-args: --optimize --optimize-runs 200
          # solc-version: 0.6.12
          # echidna-version: v2.0.3
          # solc-version: 0.8.13
